### ISSUE TITLE
Is this line an error?

### ISSUE THREAD

**Issue by mwt0530** [juntaki/bucketsync#1]
https://github.com/juntaki/bucketsync/blob/fb944141ea525655e23c0fceb0310e3ef87a5609/lib/fuse.go#L43
uuid.NewV4() return uuid, err

**Comment by juntaki** [comment]
Thank you for reporting. It is because uuid package API change. I will fix it soon!
https://github.com/satori/go.uuid/issues/66

**Comment by juntaki** [comment]
Fixed at https://github.com/juntaki/bucketsync/commit/6bb0f7c2d237bd6c3ec5a4e749cfbcbdaf8d2887
